trigger:
  branches:
    include:
      - development #only run on development branch

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.12"

  - script: | # install dependencies from requirements.txt file
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: "Install dependencies"

  - script: |
      pytest
    displayName: "Run tests"
